apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm-app-deployment
spec:
  replicas: 1 # Number of copies you want running
  selector:
    matchLabels:
      app: npm-app
  template:
    metadata:
      labels:
        app: npm-app
    spec:
      containers:
      - name: npm-app-container
        image: local-express-app:v2
        imagePullPolicy: IfNotPresent # Tells K8s to look locally instead of Docker Hub
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: npm-app-service
spec:
  type: LoadBalancer # Exposes the app to your local machine
  ports:
  - port: 80         # The port you will type into your browser (localhost:80)
    targetPort: 3000 # The port your app is listening on inside the container
  selector:
    app: npm-app
